### ISSUE TITLE
XOR generates a spurious warning message

### ISSUE THREAD

**Issue by AK6DN** [Rhialto/macro11#1]
There is an error in macro11 in processing the XOR instruction. In assemble.c it shares code with JSR but JSR will (and should throw an error/warning) on:

JSR   Rm,Rn

whereas 

XOR Rm,Rn

is perfectly valid. A warning is generated on the XOR (""JSR Rn,Rm is illegal") but should not be. The generated binary code is correct, it is just a spurious warning.

The simple fix is to change line 1499 of assemble.c from:

    if ((mode.type & 070) == 0) {

to

    if (op->value == I_JSR && (mode.type & 070) == 0) {

to make it only apply to the JSR instruction, not the XOR instruction.

**Comment by Rhialto** [comment]
Thanks for the report. It looks like I've introduced that problem when I added the checks for the operands of JSR. I'll change this and add test cases for xor in the tests.

**Comment by AK6DN** [comment]
Resolved in July 11 2016 commit. Thanks!
